#ifndef __PINOUT_H__
#define __PINOUT_H__
#include "driver/gpio.h" 

//KEYPAD PINS
#define KEYPAD_ROW1_PIN GPIO_NUM_4 //13
#define KEYPAD_ROW2_PIN GPIO_NUM_5 //12
#define KEYPAD_ROW3_PIN GPIO_NUM_6 //27
#define KEYPAD_ROW4_PIN GPIO_NUM_7 //33
#define KEYPAD_COL1_PIN GPIO_NUM_3 //15
#define KEYPAD_COL2_PIN GPIO_NUM_46 //32
#define KEYPAD_COL3_PIN GPIO_NUM_9 //14

//MOTOR PINS
#define MOTOR_GPIO_IN1 47//GPIO_NUM_20 //SCL
#define MOTOR_GPIO_IN2 48//GPIO_NUM_22 //SDA

//FINGERPRINT SCANNER PINS
#define FINGER_TX_PIN GPIO_NUM_17 //GPIO_NUM_8 
#define FINGER_RX_PIN GPIO_NUM_18 //GPIO_NUM_7
#define FINGER_TOUCHIC_PIN GPIO_NUM_8 //GPIO_NUM_38

#define FINGER_ENROLL_PIN GPIO_NUM_34 //GENERAL GPIO JUST FOR DEBUGGING

//LCD DISPLAY PINS
#define LED_PWM_PIN GPIO_NUM_12 //GPIO_NUM_21
#define DISP_SPI_MOSI GPIO_NUM_11
#define DISP_SPI_CLK GPIO_NUM_13
#define DISP_SPI_MISO (-1) //Unused
#define DISP_SPI_DC GPIO_NUM_21
#define DISP_SPI_RST GPIO_NUM_14
#define DISP_SPI_CS GPIO_NUM_10


#endif
