// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: lcd1

#include "../ui.h"
#define LV_SIZE_CONTENT 1

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL, NULL);
    // lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags

    static lv_style_t backgroundStyle;
    lv_style_init(&backgroundStyle);
    lv_style_set_bg_color(&backgroundStyle, LV_STATE_DEFAULT, lv_color_hex(0x000000));
    lv_obj_add_style(ui_MainScreen, LV_OBJ_PART_MAIN, &backgroundStyle);

    // Text Styles
    static lv_style_t text48Style;
    lv_style_init(&text48Style);
    lv_style_set_text_color(&text48Style, LV_STATE_DEFAULT, lv_color_hex(0xFFFFFF));
    lv_style_set_text_font(&text48Style, LV_STATE_DEFAULT, &lv_font_montserrat_48);

    static lv_style_t text40Style;
    lv_style_init(&text40Style);
    lv_style_set_text_color(&text40Style, LV_STATE_DEFAULT, lv_color_hex(0xFFFFFF));
    lv_style_set_text_font(&text40Style, LV_STATE_DEFAULT, &lv_font_montserrat_40);

    static lv_style_t text30Style;
    lv_style_init(&text30Style);
    lv_style_set_text_color(&text30Style, LV_STATE_DEFAULT, lv_color_hex(0xFFFFFF));
    lv_style_set_text_font(&text30Style, LV_STATE_DEFAULT, &lv_font_montserrat_30);

    static lv_style_t text18Style;
    lv_style_init(&text18Style);
    lv_style_set_text_color(&text18Style, LV_STATE_DEFAULT, lv_color_hex(0xFFFFFF));
    lv_style_set_text_font(&text18Style, LV_STATE_DEFAULT, &lv_font_montserrat_18);

    static lv_style_t textStyle;
    lv_style_init(&textStyle);
    lv_style_set_text_color(&textStyle, LV_STATE_DEFAULT, lv_color_hex(0xFFFFFF));

    ui_BackgroundImage = lv_img_create(ui_MainScreen, NULL);
    lv_img_set_src(ui_BackgroundImage, &ui_img_lcd_bg2_png);
    lv_obj_set_width(ui_BackgroundImage, 240);  /// 1
    lv_obj_set_height(ui_BackgroundImage, 320); /// 1
    lv_obj_align(ui_BackgroundImage, NULL, LV_ALIGN_CENTER, 0, 0);
    // lv_obj_add_flag(ui_BackgroundImage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_BackgroundImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_bg_img_src(ui_BackgroundImage, &TemporaryImage, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorPanel = lv_obj_create(ui_BackgroundImage, NULL);
    lv_obj_set_width(ui_ColorPanel, 240);
    lv_obj_set_height(ui_ColorPanel, 320);
    lv_obj_align(ui_ColorPanel, NULL, LV_ALIGN_CENTER, 0, 0);
    static lv_style_t colorPanelStyle;
    lv_style_init(&colorPanelStyle);
    lv_style_set_bg_color(&colorPanelStyle, LV_STATE_DEFAULT, lv_color_hex(0x000000));
    lv_style_set_bg_opa(&colorPanelStyle, LV_STATE_DEFAULT, 125);
    lv_style_set_border_width(&colorPanelStyle, LV_STATE_DEFAULT, 0);
    lv_style_set_radius(&colorPanelStyle, LV_STATE_DEFAULT, 14);
    lv_obj_add_style(ui_ColorPanel, LV_OBJ_PART_MAIN, &colorPanelStyle);
    // lv_obj_clear_flag(ui_ColorPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    // lv_obj_set_style_local_bg_color(ui_ColorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_ColorPanel, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockIcon = lv_img_create(ui_ColorPanel, NULL);
    lv_img_set_src(ui_LockIcon, &ui_img_locked_png);
    lv_obj_set_width(ui_LockIcon, 64);  /// 1
    lv_obj_set_height(ui_LockIcon, 64); /// 1
    // lv_obj_set_x(ui_LockIcon, 0);
    // lv_obj_set_y(ui_LockIcon, -100);
    lv_obj_align(ui_LockIcon, NULL, LV_ALIGN_CENTER, 0, -100);
    // lv_obj_clear_flag(ui_LockIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_UnlockIcon = lv_img_create(ui_ColorPanel, NULL);
    lv_img_set_src(ui_UnlockIcon, &ui_img_unlocked_png);
    lv_obj_set_width(ui_UnlockIcon, 64);  /// 1
    lv_obj_set_height(ui_UnlockIcon, 64); /// 1
    // lv_obj_set_x(ui_UnlockIcon, 0);
    // lv_obj_set_y(ui_UnlockIcon, -100);
    lv_obj_align(ui_UnlockIcon, NULL, LV_ALIGN_CENTER, 0, -100);
    // lv_obj_add_flag(ui_UnlockIcon, LV_OBJ_FLAG_HIDDEN);                                                                                                                                                                                                         /// Flags
    lv_obj_set_hidden(ui_UnlockIcon, true);
    // lv_obj_clear_flag(ui_UnlockIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_TimeLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_TimeLabel, 0);
    // lv_obj_set_y(ui_TimeLabel, -15);
    lv_label_set_align(ui_TimeLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "12:59");
    lv_obj_add_style(ui_TimeLabel, LV_OBJ_PART_MAIN, &text48Style);
    lv_obj_align(ui_TimeLabel, NULL, LV_ALIGN_CENTER, 0, -15);
    lv_obj_set_auto_realign(ui_TimeLabel, true);
    // lv_obj_clear_flag(ui_TimeLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    // lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_TitleLabel, 0);
    // lv_obj_set_y(ui_TitleLabel, 86);
    lv_label_set_align(ui_TitleLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_TitleLabel, "TITLE");
    lv_obj_add_style(ui_TitleLabel, LV_OBJ_PART_MAIN, &text18Style);
    lv_obj_align(ui_TitleLabel, NULL, LV_ALIGN_CENTER, 0, 85);
    lv_obj_set_auto_realign(ui_TitleLabel, true);
    // lv_obj_clear_flag(ui_TitleLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    // lv_obj_set_style_text_color(ui_TitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_TitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_TitleLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AMPMLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_AMPMLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_AMPMLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_AMPMLabel, 70);
    // lv_obj_set_y(ui_AMPMLabel, -27);
    lv_label_set_align(ui_AMPMLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_AMPMLabel, "PM");
    lv_obj_add_style(ui_AMPMLabel, LV_OBJ_PART_MAIN, &textStyle);
    lv_obj_align(ui_AMPMLabel, NULL, LV_ALIGN_CENTER, 80, -27);
    lv_obj_set_auto_realign(ui_AMPMLabel, true);
    // lv_obj_clear_flag(ui_AMPMLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    // lv_obj_set_style_text_color(ui_AMPMLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_AMPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon1Bar = lv_img_create(ui_ColorPanel, NULL);
    lv_img_set_src(ui_WifiIcon1Bar, &ui_img_wifi_icon1_png);
    lv_obj_set_width(ui_WifiIcon1Bar, 32);  /// 1
    lv_obj_set_height(ui_WifiIcon1Bar, 32); /// 1
    // lv_obj_set_x(ui_WifiIcon1Bar, 94);
    // lv_obj_set_y(ui_WifiIcon1Bar, -138);
    lv_obj_align(ui_WifiIcon1Bar, NULL, LV_ALIGN_CENTER, 94, -138);
    // lv_obj_add_flag(ui_WifiIcon1Bar, LV_OBJ_FLAG_HIDDEN);                                                                                                                                                                                                         /// Flags
    lv_obj_set_hidden(ui_WifiIcon1Bar, true);
    // lv_obj_clear_flag(ui_WifiIcon1Bar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_WifiIcon2Bar = lv_img_create(ui_ColorPanel, NULL);
    lv_img_set_src(ui_WifiIcon2Bar, &ui_img_wifi_icon2_png);
    lv_obj_set_width(ui_WifiIcon2Bar, 32);  /// 1
    lv_obj_set_height(ui_WifiIcon2Bar, 32); /// 1
    // lv_obj_set_x(ui_WifiIcon2Bar, 94);
    // lv_obj_set_y(ui_WifiIcon2Bar, -138);
    lv_obj_align(ui_WifiIcon2Bar, NULL, LV_ALIGN_CENTER, 94, -138);
    // lv_obj_add_flag(ui_WifiIcon2Bar, LV_OBJ_FLAG_HIDDEN);                                                                                                                                                                                                         /// Flags
    lv_obj_set_hidden(ui_WifiIcon2Bar, true);
    // lv_obj_clear_flag(ui_WifiIcon2Bar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_WifiIcon3Bar = lv_img_create(ui_ColorPanel, NULL);
    lv_img_set_src(ui_WifiIcon3Bar, &ui_img_wifi_icon3_png);
    lv_obj_set_width(ui_WifiIcon3Bar, 32);  /// 1
    lv_obj_set_height(ui_WifiIcon3Bar, 32); /// 1
    // lv_obj_set_x(ui_WifiIcon3Bar, 94);
    // lv_obj_set_y(ui_WifiIcon3Bar, -138);
    lv_obj_align(ui_WifiIcon3Bar, NULL, LV_ALIGN_CENTER, 94, -138);
    // lv_obj_clear_flag(ui_WifiIcon3Bar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_HelloLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_HelloLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_HelloLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_HelloLabel, 0);
    // lv_obj_set_y(ui_HelloLabel, -60);
    lv_label_set_align(ui_HelloLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_HelloLabel, "Hello");
    lv_obj_add_style(ui_HelloLabel, LV_OBJ_PART_MAIN, &text30Style);
    lv_obj_align(ui_HelloLabel, NULL, LV_ALIGN_CENTER, 0, -60);
    lv_obj_set_auto_realign(ui_HelloLabel, true);
    // lv_obj_add_flag(ui_HelloLabel, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_hidden(ui_HelloLabel, true);
    // lv_obj_set_style_text_color(ui_HelloLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_HelloLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_HelloLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FirstNameLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_FirstNameLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FirstNameLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_FirstNameLabel, 0);
    // lv_obj_set_y(ui_FirstNameLabel, 36);
    lv_label_set_align(ui_FirstNameLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_FirstNameLabel, "FIRST");
    lv_obj_add_style(ui_FirstNameLabel, LV_OBJ_PART_MAIN, &text40Style);
    lv_obj_align(ui_FirstNameLabel, NULL, LV_ALIGN_CENTER, 0, 36);
    lv_obj_set_auto_realign(ui_FirstNameLabel, true);
    // lv_obj_add_flag(ui_FirstNameLabel, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_hidden(ui_FirstNameLabel, true);
    // lv_obj_set_style_text_color(ui_FirstNameLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_FirstNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_FirstNameLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastNameLabel = lv_label_create(ui_ColorPanel, NULL);
    lv_obj_set_width(ui_LastNameLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LastNameLabel, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_LastNameLabel, 0);
    // lv_obj_set_y(ui_LastNameLabel, 80);
    lv_label_set_align(ui_LastNameLabel, LV_LABEL_ALIGN_CENTER);
    lv_label_set_text(ui_LastNameLabel, "LAST");
    lv_obj_add_style(ui_LastNameLabel, LV_OBJ_PART_MAIN, &text40Style);
    lv_obj_align(ui_LastNameLabel, NULL, LV_ALIGN_CENTER, 0, 80);
    lv_obj_set_auto_realign(ui_LastNameLabel, true);
    // lv_obj_add_flag(ui_LastNameLabel, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_hidden(ui_LastNameLabel, true);
    // lv_obj_set_style_text_color(ui_LastNameLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_LastNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_LastNameLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
}
